export const data = [
  {
    name: 'Art',
    url: '/categories/art',
    description:
      'Art is the study of the principles of aesthetics and the principles of beauty.',
    icon: 'https://img.icons8.com/external-flaticons-lineal-color-flat-icons/64/000000/external-art-online-education-flaticons-lineal-color-flat-icons.png',
    subCategories: [
      {
        name: 'Painting',
        description: 'Find mentor in painting',
        image: 'paint-brush',
        url: '/painting',
        category: 'Art',
      },
      {
        name: 'Sculpting',
        description: 'Find mentor in sculpting',
        image: 'sculpture',
        url: '/sculpting',
        category: 'Art',
      },
      {
        name: 'Drawing',
        description: 'Find mentor in drawing',
        image: 'drawing',
        url: '/drawing',
        category: 'Art',
      },
      {
        name: 'Photography',
        description: 'Find mentor in photography',
        image: 'camera',
        url: '/photography',
        category: 'Art',
      },
      {
        name: 'Graphic Design',
        description: 'Find mentor in design',
        image: 'design',
        url: '/graphic-design',
        category: 'Art',
      },
    ],
  },
  {
    name: 'Crafts',
    url: '/categories/craft',
    description:
      'Crafts is an art, trade, or occupation requiring special skill, especially manual skill.',
    icon: 'https://img.icons8.com/external-flaticons-lineal-color-flat-icons/64/000000/external-craft-edutainment-flaticons-lineal-color-flat-icons.png',
    subCategories: [
      {
        name: 'Pottery',
        description: 'Find mentor in making pottery',
        image: 'paint-brush',
        url: '/pottery',
        category: 'Crafts',
      },
      {
        name: 'Knitting',
        description: 'Find mentor in making knitting',
        image: 'sculpture',
        url: '/knitting',
        category: 'Crafts',
      },
      {
        name: 'Crochet',
        description: 'Find mentor in making crochet',
        image: 'drawing',
        url: '/crochet',
        category: 'Crafts',
      },
      {
        name: 'Weaving',
        description: 'Find mentor in craft weaving',
        image: 'camera',
        url: '/weaving',
        category: 'Crafts',
      },
    ],
  },
  {
    name: 'Music',
    url: '/categories/music',
    description: 'Music is a form of art that uses sound organized in time.',
    icon: 'https://img.icons8.com/office/16/000000/maracas.png',
    subCategories: [
      {
        name: 'Piano',
        description: 'Find mentor in music',
        image: 'paint-brush',
        url: '/piano',
        category: 'Music',
      },
      {
        name: 'Guitar',
        description: 'Find mentor in music',
        image: 'sculpture',
        url: '/guitar',
        category: 'Music',
      },
      {
        name: 'Drums',
        description: 'Find mentor in in music',
        image: 'drums',
        url: '/drums',
        category: 'Music',
      },
      {
        name: 'Violin',
        description: 'Find mentor in music',
        image: 'camera',
        url: '/violin',
        category: 'Music',
      },
    ],
  },
  {
    name: 'Technology',
    url: '/categories/tech',
    description:
      'Technology is the continually developing result of accumulated knowledge and application in all techniques, skills, methods, and processes used in industrial production and scientific research',
    icon: 'https://img.icons8.com/dusk/64/000000/computer.png',
    subCategories: [
      {
        name: 'Electronic',
        description: 'Find mentor in electronics',
        image: 'sculpture',
        url: '/electronics',
        category: 'Technology',
        sub: [
          {
            name: 'Computer',
            description: 'Find mentor in computer electronics',
            image: 'camera',
            url: '/computer',
            category: 'Electronic',
          },
          {
            name: 'Camera',
            description: 'Find mentor in camera electronics',
            image: 'camera',
            url: '/camera',
            category: 'Electronic',
          },
          {
            name: 'Wearables',
            description: 'Find mentor in Wearables electronics',
            image: 'camera',
            url: '/wearables',
            category: 'Electronic',
          },
          {
            name: 'Mobile Devices',
            description: 'Find mentor in mobile electronics',
            image: 'camera',
            url: '/mobile-devices',
            category: 'Electronic',
          },
        ],
      },
      {
        name: 'Computer Programming',
        description: 'Find mentor in Computer Programming',
        image: 'drawing',
        url: '/programming',
        category: 'Technology',
        sub: [
          {
            name: 'Data Science',
            description: 'Find mentor in Data Science',
            image: 'camera',
            url: '/web-development',
            category: 'Computer Programming',
          },
          {
            name: 'Software Development',
            description: 'Find mentor in Software Development',
            image: 'camera',
            url: '/software-development',
            category: 'Computer Programming',
          },
          {
            name: 'Blockchain',
            description: 'Find mentor in Blockchain',
            image: 'camera',
            url: '/blockchain',
            category: 'Computer Programming',
          },
        ],
      },
    ],
  },
];
